name: wolfPKCS11 Sanitizer Tests

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  sanitizer:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # msan disabled due to too many failures
        # tsan disabled due to weird failures
        sanitizer: [asan, ubsan]
        tpm: [false, true]

    steps:
#pull wolfPKCS11
    - uses: actions/checkout@v4
      with:
        submodules: true

#setup wolfssl
    - uses: actions/checkout@v4
      with:
        repository: wolfssl/wolfssl
        path: wolfssl
    - name: wolfssl autogen
      working-directory: ./wolfssl
      run: ./autogen.sh
    - name: wolfssl configure with ${{ matrix.sanitizer }}
      working-directory: ./wolfssl
      run: |
        export CC=clang
        export CXX=clang++
        case "${{ matrix.sanitizer }}" in
          "asan")
            export CFLAGS="-fsanitize=address -fno-omit-frame-pointer -g"
            export LDFLAGS="-fsanitize=address"
            ;;
          "msan")
            export CFLAGS="-fsanitize=memory -fno-omit-frame-pointer -g"
            export LDFLAGS="-fsanitize=memory"
            ;;
          "tsan")
            export CFLAGS="-fsanitize=thread -fno-omit-frame-pointer -g"
            export LDFLAGS="-fsanitize=thread"
            ;;
          "ubsan")
            export CFLAGS="-fsanitize=undefined -fno-omit-frame-pointer -g"
            export LDFLAGS="-fsanitize=undefined"
            ;;
        esac
        ./configure --enable-cryptocb --enable-aescfb --enable-rsapss --enable-keygen --enable-pwdbased --enable-scrypt \
            C_EXTRA_FLAGS="-DWOLFSSL_PUBLIC_MP -DWC_RSA_DIRECT"
    - name: wolfssl make
      working-directory: ./wolfssl
      run: |
        make
    - name: wolfssl make install
      working-directory: ./wolfssl
      run: |
        sudo make install
        sudo ldconfig

#setup ibmswtpm2 (only if TPM enabled)
    - uses: actions/checkout@v4
      if: matrix.tpm
      with:
        repository: kgoldman/ibmswtpm2
        path: ibmswtpm2
    - name: ibmswtpm2 make
      if: matrix.tpm
      working-directory: ./ibmswtpm2/src
      run: |
          make
          ./tpm_server &

#setup wolftpm (only if TPM enabled)
    - uses: actions/checkout@v4
      if: matrix.tpm
      with:
        repository: wolfssl/wolftpm
        path: wolftpm
    - name: wolftpm autogen
      if: matrix.tpm
      working-directory: ./wolftpm
      run: ./autogen.sh
    - name: wolftpm configure with ${{ matrix.sanitizer }}
      if: matrix.tpm
      working-directory: ./wolftpm
      run: |
        export CC=clang
        export CXX=clang++
        case "${{ matrix.sanitizer }}" in
          "asan")
            export CFLAGS="-fsanitize=address -fno-omit-frame-pointer -g"
            export LDFLAGS="-fsanitize=address"
            ;;
          "msan")
            export CFLAGS="-fsanitize=memory -fno-omit-frame-pointer -g"
            export LDFLAGS="-fsanitize=memory"
            ;;
          "tsan")
            export CFLAGS="-fsanitize=thread -fno-omit-frame-pointer -g"
            export LDFLAGS="-fsanitize=thread"
            ;;
          "ubsan")
            export CFLAGS="-fsanitize=undefined -fno-omit-frame-pointer -g"
            export LDFLAGS="-fsanitize=undefined"
            ;;
        esac
        ./configure --enable-swtpm
    - name: wolftpm make
      if: matrix.tpm
      working-directory: ./wolftpm
      run: |
        make
    - name: wolftpm make install
      if: matrix.tpm
      working-directory: ./wolftpm
      run: |
          sudo make install
          sudo ldconfig

#setup wolfPKCS11
    - name: wolfpkcs11 autogen
      run: ./autogen.sh
    - name: wolfpkcs11 configure with ${{ matrix.sanitizer }}
      run: |
        export CC=clang
        export CXX=clang++
        case "${{ matrix.sanitizer }}" in
          "asan")
            export CFLAGS="-fsanitize=address -fno-omit-frame-pointer -g"
            export LDFLAGS="-fsanitize=address"
            ;;
          "msan")
            export CFLAGS="-fsanitize=memory -fno-omit-frame-pointer -g"
            export LDFLAGS="-fsanitize=memory"
            ;;
          "tsan")
            export CFLAGS="-fsanitize=thread -fno-omit-frame-pointer -g"
            export LDFLAGS="-fsanitize=thread"
            ;;
          "ubsan")
            export CFLAGS="-fsanitize=undefined -fno-omit-frame-pointer -g"
            export LDFLAGS="-fsanitize=undefined"
            ;;
        esac
        if [ "${{ matrix.tpm }}" = "true" ]; then
          case "${{ matrix.sanitizer }}" in
            "asan")
              ./configure --enable-singlethreaded --enable-wolftpm --disable-dh C_EXTRA_FLAGS="-DWOLFPKCS11_TPM_STORE"
              ;;
            "msan")
              ./configure --enable-singlethreaded --enable-wolftpm --disable-dh C_EXTRA_FLAGS="-DWOLFPKCS11_TPM_STORE"
              ;;
            "tsan")
              ./configure --enable-singlethreaded --enable-wolftpm --disable-dh C_EXTRA_FLAGS="-DWOLFPKCS11_TPM_STORE"
              ;;
            "ubsan")
              ./configure --enable-singlethreaded --enable-wolftpm --disable-dh C_EXTRA_FLAGS="-DWOLFPKCS11_TPM_STORE"
              ;;
          esac
        else
          ./configure
        fi
    - name: wolfpkcs11 make
      run: |
        make
    - name: wolfpkcs11 make check
      run: |
        if [ "${{ matrix.sanitizer }}" = "tsan" ]; then
          export TSAN_OPTIONS="suppressions=$PWD/tsan_suppressions.txt"
        fi
        if [ "${{ matrix.tpm }}" = "true" ]; then
          ./tests/pkcs11str && ./tests/pkcs11test
        else
          make check
        fi

# capture logs on failure
    - name: Upload failure logs
      if: failure() || cancelled()
      uses: actions/upload-artifact@v4
      with:
        name: wolfpkcs11-${{ matrix.sanitizer }}-${{ matrix.tpm && 'tpm' || 'notpm' }}-test-logs
        path: |
          test-suite.log
        retention-days: 5
